### ISSUE TITLE
Normalize template for my own dataset.

### ISSUE THREAD

**Issue by qaz8788817** [NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap#4]
Hi.
Thank you very much for sharing the preprocessing code earlier. During the course of my research, I encountered a few questions, and I was hoping you could kindly help clarify them for me.

Firstly, I'm curious to know if "normalized_2D_final.ply" and "normalized_3D.ply" are universally applicable to all facial models. And if I need to recreate "normalized_2D.ply" and "normalized_3D.ply" for my own dataset, could you please advise on the steps to take after obtaining the noiseless 3D template mesh Vs?
Here is my matlab code to acquire noiseless 3D template mesh:
![image](https://github.com/NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap/assets/73918947/a43f78c4-9d18-4d80-88d5-e86d04d72aea)
![image](https://github.com/NaughtyZZ/3D_facial_shape_attribute_translation_ssgmap/assets/73918947/5a959162-ac8a-40ca-96ec-13a26fb622b4)

Secondly, I am wondering how the coordinates of "noseTip" are defined?

Thank you very much for considering my queries. Your guidance and insights are highly appreciated.

**Comment by NaughtyZZ** [comment]
1. You can either use the provided 3D template or the one you computed from the ensemble of all TU models. The 2D template is unfolded by a 3D template and bridges the gap bettween the 3D faces and the UV maps. Since the correspondences of vertices are one-by-one, you need to do nothing except for feeding the normalized vertices coordinates to the network.

2. The coordinates of "noseTip" is located at the nose tip given by a fixed vetex index. For the inputs of the network for training, we need to substract the given noiseTip first and then normalize the vertices with some common factors in 3 axis.

Thank you for your attention.
